# Generated by Django 6.0.4 on 2026-04-23 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_people', models.IntegerField()),
                ('contact_email', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('transaction_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
            options={
                'db_table': 'Payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creator_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('admin_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('creator', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, to='bookings.payment')),
            ],
            options={
                'db_table': 'Revenue',
                'managed': True,
            },
        ),
    ]
