# Generated by Django 6.0.3 on 2026-04-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(db_column='booking_id', primary_key=True, serialize=False)),
                ('number_of_people', models.IntegerField(db_column='number_of_people')),
                ('contact_email', models.EmailField(db_column='contact_email', max_length=254)),
                ('contact_phone', models.CharField(db_column='contact_phone', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELED', 'Đã hủy')], db_column='status', default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
    ]
