# Generated by Django 6.0.3 on 2026-04-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
    ]
