# Generated by Django 6.0.3 on 2026-04-06 06:11

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=100, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=150, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('role', models.CharField(db_column='role', default='USER', max_length=20)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='date_joined')),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=150)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
