# Generated by Django 6.0.3 on 2026-04-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(db_column='location_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, db_column='latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='longitude', null=True)),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(db_column='tour_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('price', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateTimeField(blank=True, db_column='start_date', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='end_date', null=True)),
                ('max_people', models.IntegerField(blank=True, db_column='max_people', null=True)),
                ('available_slots', models.IntegerField(blank=True, db_column='available_slots', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], db_column='status', default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'Tours',
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('image_id', models.AutoField(db_column='image_id', primary_key=True, serialize=False)),
                ('image', models.ImageField(db_column='image_url', max_length=500, upload_to='tours/')),
            ],
            options={
                'db_table': 'TourImages',
            },
        ),
    ]
