# Generated by Django 6.0.3 on 2026-04-06 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='creator',
            field=models.ForeignKey(blank=True, db_column='creator_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.location'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour'),
        ),
    ]
